### ISSUE TITLE
Add disclaimer to receive on-chain funds about min collateral for trading

### ISSUE THREAD

**Issue by holzeis** [get10101/10101#2098] opened 2024-02-26 13:02 UTC
User fund the app with 250k sats just to learn that this is slightly to less because of the fees. Providing a disclaimer when creating the bitcoin address, should help the user to fund the wallet with sufficient funds.

**Comment by luckysori** [comment] 2024-02-27 09:11
Duplicate of X.

**Closed by luckysori** 2024-02-27 09:11 UTC
Labels: idea
