### ISSUE TITLE
Invalid state: Received sub channel offer but a non closed sub channel already exists

### ISSUE THREAD

**Issue by da-kami** [get10101/10101#399] opened 2023-04-12 20:48 UTC
This happened on:

<img width="315" alt="image" src="https://user-images.githubusercontent.com/5557790/231579822-ac78dd70-8a4f-4f64-bbe8-840aa457fa61.png">

Note: I don't think any fixes were applied since I branched off from `main` so I am reporting this as bug assuming that it can happen on `main` as well.
@luckysori if this is a known problem feel free to close.

--- 

What happened:

I opened a `long` position and closed it without problems.

When opening another `short` position I ran into this error on the app:

```
flutter: | 2023-04-12 16:32:25.125 | LogLevel.DEBUG | Filling order with id: 95d000a6-ed4f-4579-aede-2fa16e1a7b58
flutter: | 2023-04-12 16:32:25.609 | LogLevel.INFO | Sent trade request to coordinator successfully
flutter: | 2023-04-12 16:32:27.467 | LogLevel.DEBUG | Publishing event WalletInfoUpdateNotification(WalletInfo { balances: Balances { on_chain: 0, lightning: 3672 }, history: [WalletHistoryItem { flow: Inbound, amount_sats: 1006, timestamp: 1681330203, status: Confirmed, wallet_type: Trade { order_id: "3f200e4f-5caf-47bd-95b9-ce4ba42819ce" } }, WalletHistoryItem { flow: Outbound, amount_sats: 1000, timestamp: 1681329857, status: Confirmed, wallet_type: Trade { order_id: "54aa823d-235f-4620-b515-e3f29915c644" } }] })
flutter: | 2023-04-12 16:32:28.162 | LogLevel.DEBUG | Processing DLC channel message
flutter: | 2023-04-12 16:32:28.175 | LogLevel.ERROR | Unable to process incoming messages: Invalid state: Received sub channel offer but a non closed sub channel already exists

```

After that the app's trading was basically unusable, because any consecutive order would fail with:

```
flutter: | 2023-04-12 16:35:37.556 | LogLevel.DEBUG | Publishing event OrderUpdateNotification(Order { id: b3efc728-9d4d-45e3-a0a7-58b9fa847d7e, leverage: 2.0, quantity: 0.5977, contract_symbol: BtcUsd, direction: Long, order_type: Market, state: Open, creation_timestamp: 2023-04-12 20:35:37.0 +00:00:00 })
flutter: | 2023-04-12 16:35:37.558 | LogLevel.DEBUG | Filling order with id: b3efc728-9d4d-45e3-a0a7-58b9fa847d7e
flutter: | 2023-04-12 16:35:38.016 | LogLevel.ERROR | Failed to execute trade for order Some(b3efc728-9d4d-45e3-a0a7-58b9fa847d7e): TradeResponse: Could not post trade to coordinator: {"error":"Could not handle trade request: Could not propose dlc channel: Invalid state: Received sub channel offer but a non closed sub channel already exists"}
flutter: | 2023-04-12 16:35:38.022 | LogLevel.DEBUG | Publishing event OrderUpdateNotification(Order { id: b3efc728-9d4d-45e3-a0a7-58b9fa847d7e, leverage: 2.0, quantity: 0.5977, contract_symbol: BtcUsd, direction: Long, order_type: Market, state: Failed { reason: TradeResponse }, creation_timestamp: 2023-04-12 20:35:37.0 +00:00:00 })
flutter: | 2023-04-12 16:35:43.169 | LogLevel.DEBUG | Publishing event WalletInfoUpdateNotification(WalletInfo { balances: Balances { on_chain: 0, lightning: 3672 }, history: [WalletHistoryItem { flow: Inbound, amount_sats: 1006, timestamp: 1681330203, status: Confirmed, wallet_type: Trade { order_id: "3f200e4f-5caf-47bd-95b9-ce4ba42819ce" } }, WalletHistoryItem { flow: Outbound, amount_sats: 1000, timestamp: 1681329857, status: Confirmed, wallet_type: Trade { order_id: "54aa823d-235f-4620-b515-e3f29915c644" } }] })
```

Coordinator:

The first position was closed and finalized correctly:

```
2023-04-12 20:10:03  INFO coordinator::node: Closing position order_id=3f200e4f-5caf-47bd-95b9-ce4ba42819ce trader_pk=02b9defa97c2d73c805af3c7ee9f00a8139bd6dc54c7a93e488ce45c747e52ad40
2023-04-12 20:10:03 DEBUG coordinator::node: Settling position of 1006 with 02b9defa97c2d73c805af3c7ee9f00a8139bd6dc54c7a93e488ce45c747e52ad40
2023-04-12 20:10:03  INFO ln_dlc_node::node::dlc_channel: Settling DLC channel collaboratively channel_id=74ee393e87622f1010216b81fd0dd8f6fbbf616f87f9a8c5ace877cec9bba335 accept_settlement_amount=1006
2023-04-12 20:10:09 DEBUG coordinator::node: Processing DLC channel message from=02b9defa97c2d73c805af3c7ee9f00a8139bd6dc54c7a93e488ce45c747e52ad40 msg=CloseAccept
2023-04-12 20:10:09  INFO lightning::chain::channelmonitor: Applying update to monitor 74ee393e87622f1010216b81fd0dd8f6fbbf616f87f9a8c5ace877cec9bba335, bringing update_id from 8 to 9 with 1 changes.
2023-04-12 20:10:09 DEBUG lightning::ln::channel: Received valid commitment_signed from peer in channel 74ee393e87622f1010216b81fd0dd8f6fbbf616f87f9a8c5ace877cec9bba335, updating HTLC state and responding with a revoke_and_ack.
2023-04-12 20:10:09  INFO lightning::chain::channelmonitor: Applying update to monitor 74ee393e87622f1010216b81fd0dd8f6fbbf616f87f9a8c5ace877cec9bba335, bringing update_id from 9 to 10 with 1 changes.
2023-04-12 20:10:09 DEBUG coordinator::node: Sending DLC channel message to=02b9defa97c2d73c805af3c7ee9f00a8139bd6dc54c7a93e488ce45c747e52ad40 msg=CloseConfirm
2023-04-12 20:10:14 DEBUG coordinator::node: Processing DLC channel message from=02b9defa97c2d73c805af3c7ee9f00a8139bd6dc54c7a93e488ce45c747e52ad40 msg=CloseFinalize
2023-04-12 20:10:14 DEBUG lightning::ln::channel: Received a valid revoke_and_ack for channel 74ee393e87622f1010216b81fd0dd8f6fbbf616f87f9a8c5ace877cec9bba335 with no reply necessary.
```

Besides that the coordinator does not really report any error - which is odd. According to the logs the position is being set up...

```
2023-04-12 20:31:53 DEBUG lightning::ln::peer_handler: Error handling message from 02b9defa97c2d73c805af3c7ee9f00a8139bd6dc54c7a93e488ce45c747e52ad40; ignoring: No existing channels for node_announcement
2023-04-12 20:32:20 DEBUG ln_dlc_node::node: Announcing node on [IPv4 { addr: [10, 60, 173, 96], port: 9045 }]
2023-04-12 20:32:20 DEBUG lightning::ln::peer_handler: Broadcasting NodeAnnouncement after passing it to our own RoutingMessageHandler.
2023-04-12 20:32:24 ERROR coordinator::orderbook::trading: Could not notify maker - we should fail here and get another match if possible
2023-04-12 20:32:24 DEBUG coordinator::orderbook::trading: Successfully notified taker
2023-04-12 20:32:25  INFO coordinator::node: Opening position
2023-04-12 20:32:25 DEBUG coordinator::node: Proposing dlc channel event_id="btcusd1681936344"
2023-04-12 20:32:25 DEBUG reqwest::connect: starting new connection: https://oracle.holzeis.me/
2023-04-12 20:32:53 DEBUG lightning::ln::peer_handler: Error handling message from 02b9defa97c2d73c805af3c7ee9f00a8139bd6dc54c7a93e488ce45c747e52ad40; ignoring: No existing channels for node_announcement
2023-04-12 20:33:21 DEBUG ln_dlc_node::node: Announcing node on [IPv4 { addr: [10, 60, 173, 96], port: 9045 }]
2023-04-12 20:33:21 DEBUG lightning::ln::peer_handler: Broadcasting NodeAnnouncement after passing it to our own RoutingMessageHandler.
```

**Comment by luckysori** [comment] 2023-04-14 14:18
No conclusion yet, but I've noticed that we can get the same error from the coordinator:

```
2023-04-14T14:01:54.908975756Z ERROR native::trade::order::handler: Failed to execute trade for order Some(364e7532-41b7-480f-b4ad-02bc3174b3e9): TradeResponse: Could not post trade to coordinator: {"error":"Could not handle trade request: Could not propose dlc channel: Invalid state: Received sub channel offer but a non closed sub channel already exists"}
```

These are logs from the _app_ giving us the response from the coordinator. The response is confusing because `rust-dlc` is wrongly talking about a "received sub channel offer" when in reality it is a "soon-to-be sent sub channel offer".

**Comment by holzeis** [comment] 2023-04-21 10:57
I think this bug had the same root cause as #470 closing this ticket now as it should have been fixed with #474. Please reopen if this bug is happening again.

**Comment by luckysori** [comment] 2023-04-21 11:21
Still happening to me :(

**Comment by da-kami** [comment] 2023-04-21 13:41
OK, so I just manually tested on `native` (I want to make sure this is not just happening on iOS again).
Just to make sure to describe the problem in more detail here are the details - this corresponds to the findings in the test that @luckysori wrote.

1. Opened position 1 (no problems)
2. Closed position 1 (no problems)
3. Opened position 2 (no problems)
4. Closed position 2 (no problems) -> The coordinator ran into 
5. Opened position 3 -> I ran into `Invalid state: Received sub channel offer but a non closed sub channel already exists`

Note that for the app it looks like the position was closed properly - the user can just not trade again, but the balance and channel look good, so this does not necessarily have to be a blocker if we accept that the user can only trade "two times".

Coordinator failure (position 2 close):

```
2023-04-21 13:25:49 ERROR coordinator::node: Failed to process message: Failed to handle SubChannelCloseFinalize message from 0250212ef78afa412799d3cdacbfe699e8095fb9fbf4a1655461d5535ff6546730: Invalid parameters were provided: Invalid split revocation secret from=0250212ef78afa412799d3cdacbfe699e8095fb9fbf4a1655461d5535ff6546730 kind=SubChannelCloseFinalize
```

App failure (position 3):

```
2023-04-21T13:26:00.928871Z ERROR native::trade::order::handler: Failed to execute trade for order Some(42c8f321-caec-46a8-aecc-3bcae0c2b725): TradeResponse: Could not post trade to coordinator: {"error":"Could not handle trade request: Could not propose dlc channel: Invalid state: Received sub channel offer but a non closed sub channel already exists"}
2023-04-21T13:26:00.929584Z  INFO native::db::models: Updated order state new_state=Failed order_id=42c8f321-caec-46a8-aecc-3bcae0c2b725

```

Once in that state I was unable to go on trading.

I tried:

- Wait a bit and try again: Same error
- Quit and start the app again: Same error

The error is clearly on the coordinator side, so I restarted the coordinator: 

- Restart coordinator: Same error (eventually)

This means the corrupted state on the coordinator is persisted.

**Comment by da-kami** [comment] 2023-04-21 13:42
Reconfirming that the bug reported in this ticket is actually a symptom of https://github.com/get10101/10101/issues/310

**Closed** 2023-04-22 01:39 UTC
Labels: bug, MVP, resilience
