### ISSUE TITLE
Payment is shown as pending and received

### ISSUE THREAD

**Issue by holzeis** [get10101/10101#1254] opened 2023-09-08 11:13 UTC
## What did I do?

1. Fund wallet with 100k sats
2. Pay JIT channel opening fees of 153 sats
3. Receive funds of 153 sats
4. Pay with faucet.

![IMG_09448D29B851-1](https://github.com/get10101/10101/assets/382048/c14642c4-4f72-49ea-a476-faf9fbedef09)

**Comment by Restioson** [comment] 2023-09-08 14:10
I can't reproduce this - are you sure you didn't accidentally exit out of invoice creation at some point?

Can you show the details for the pending & successful ones?

<details>
<summary>Screenshot of my state after performing steps listed</summary>

![image](https://github.com/get10101/10101/assets/6688948/08a9451d-a740-4d6f-82a0-81b322adf0d7)
![image](https://github.com/get10101/10101/assets/6688948/c3a02092-a720-40a1-86fa-fb54f1bc0d71)

</details>

**Comment by Restioson** [comment] 2023-09-08 14:19
Ah, I just managed to reproduce this. I think there must be a race condition somewhere creating the invoice twice.

**Comment by Restioson** [comment] 2023-09-08 14:39
I suppose we'd expect to see two "Successfully created invoice" logs

**Comment by bonomat** [comment] 2023-09-26 14:39
Closing as we are reworking the receive screen in #1163 which will solve this ticket.

**Closed by bonomat** 2023-09-26 14:39 UTC
Labels: bug
