### ISSUE TITLE
Failed settling position: `InvalidDlcOffer(Unacceptable)`

### ISSUE THREAD

**Issue by bonomat** [get10101/10101#2346] opened 2024-04-01 10:13 UTC
node-id: `0260f5d3f3f90551729c3df880be7214be3a0dcf7f7cc421f44cac0938554fca80`

```bash
[INFO] TIME: 2024-03-31T09:58:34.479840Z r: Received match from orderbook order_id: 711310e7-03e3-4c4f-927e-b35473a04da5
[INFO] TIME: 2024-03-31T09:58:34.480311Z r: Updated order state new_state: Filling,order_id: 711310e7-03e3-4c4f-927e-b35473a04da5
[INFO] TIME: 2024-03-31T09:58:34.587426Z r: Processing message from: 022ae8dbec1caa4dac93f07f2ebf5ad7a5dd08d375b79f11095e81b065c2155156,kind: ChannelSettleOffer
[DEBUG] TIME: 2024-03-31T09:58:34.587793Z r: Received channel message from: 022ae8dbec1caa4dac93f07f2ebf5ad7a5dd08d375b79f11095e81b065c2155156
[ERROR] TIME: 2024-03-31T09:58:34.594878Z r: Failed to execute trade: Failed to accept offer order_id: None,reason: InvalidDlcOffer(Unacceptable)
```

Ever since I'm in a broken state: 

```
[ERROR] TIME: 2024-04-01T10:09:13.995345Z r: Failed to process incoming DLC message: Failed to handle ChannelSettleOffer message from 022ae8dbec1caa4dac93f07f2ebf5ad7a5dd08d375b79f11095e81b065c2155156: Invalid state: Received settle offer while not in Established state. from: 022ae8dbec1caa4dac93f07f2ebf5ad7a5dd08d375b79f11095e81b065c2155156,kind: ChannelSettleOffer
```

Full logs: 

[2024-04-01_210948.log](https://github.com/get10101/10101/files/14822393/2024-04-01_210948.log)

**Comment by holzeis** [comment] 2024-04-01 13:02
I think that's a duplicate of https://github.com/get10101/10101/issues/2291

Try to rollback your channel state to the latest stable state in the emergency kit.

**Comment by bonomat** [comment] 2024-04-01 21:12
> I think that's a duplicate of #2291
> 
> Try to rollback your channel state to the latest stable state in the emergency kit.

Unfortunately it did not help. 

`> [WARN] TIME: 2024-04-01T21:07:06.220491Z r: Executing emergency kit! Attempting to rollback channel state to last stable state `

After the rollback: 

![image](https://github.com/get10101/10101/assets/224613/889f9401-6635-4453-b4fd-3ed3c2a41e56)

Closed the app (no dialog or anything)

when trying to close the position I get `Failed executing the DLC protocol`


```
> [INFO] TIME: 2024-04-01T21:10:22.606129Z r: Updated order state new_state: Open,order_id: ca28c7f8-9a6a-44ba-b390-427068804815
> [INFO] TIME: 2024-04-01T21:10:22.864419Z r: Received match from orderbook order_id: ca28c7f8-9a6a-44ba-b390-427068804815
> [INFO] TIME: 2024-04-01T21:10:22.864752Z r: Updated order state new_state: Filling,order_id: ca28c7f8-9a6a-44ba-b390-427068804815
> [INFO] TIME: 2024-04-01T21:10:23.002860Z r: Processing message from: 022ae8dbec1caa4dac93f07f2ebf5ad7a5dd08d375b79f11095e81b065c2155156,kind: ChannelSettleOffer
> [DEBUG] TIME: 2024-04-01T21:10:23.003155Z r: Received channel message from: 022ae8dbec1caa4dac93f07f2ebf5ad7a5dd08d375b79f11095e81b065c2155156
> [ERROR] TIME: 2024-04-01T21:10:23.004427Z r: Failed to execute trade: Failed to accept offer order_id: None,reason: InvalidDlcOffer(Unacceptable)
> [INFO] TIME: 2024-04-01T21:10:23.005992Z r: Updated order state new_state: Failed,order_id: ca28c7f8-9a6a-44ba-b390-427068804815
> [INFO] TIME: 2024-04-01T21:10:23.007511Z r: Sending message kind: ChannelReject,to: 022ae8dbec1caa4dac93f07f2ebf5ad7a5dd08d375b79f11095e81b065c2155156
> [ERROR] TIME: 2024-04-01T21:10:23.007797Z r: Failed to process incoming DLC message: Failed to handle ChannelSettleOffer message from 022ae8dbec1caa4dac93f07f2ebf5ad7a5dd08d375b79f11095e81b065c2155156: Invalid state: Received settle offer while not in Established state. from: 022ae8dbec1caa4dac93f07f2ebf5ad7a5dd08d375b79f11095e81b065c2155156,kind: ChannelSettleOffer
```



[2024-04-02_081039.log](https://github.com/get10101/10101/files/14828565/2024-04-02_081039.log)

**Comment by holzeis** [comment] 2024-04-03 05:53
I still think it's a duplicate of #2239

**Comment by bonomat** [comment] 2024-04-05 16:52
Might be related to this initial issue: I can't close my position anymore: 

![Screenshot 2024-04-06 at 3 49 42 am](https://github.com/get10101/10101/assets/224613/fad59647-fa8d-4def-8d10-156de2782eb9)

**Comment by holzeis** [comment] 2024-04-05 19:02
@bonomat could it be that your channel was stuck in the rollover again?

**Comment by bonomat** [comment] 2024-04-07 23:39
I was able to recover from this.

**Comment by holzeis** [comment] 2024-04-09 06:27
> I was able to recover from this.

I presume the rollover protocol wasn't finished

**Closed** 2024-04-09 06:42 UTC
Labels: bug, prod-environment
