### ISSUE TITLE
The app shouldn't fail to start if a electrs is down

### ISSUE THREAD

**Issue by holzeis** [get10101/10101#2430] opened 2024-04-16 10:02 UTC
It happened on production that the bitcoin node stopped and thus electrs was also not available. This lead for at least one user to the app crashing.

**Comment by bonomat** [comment] 2024-04-23 07:29
Related to #2431

**Comment by Restioson** [comment] 2024-06-03 14:45
It seems, to me, that more than just electrs being down is required. My app has launched and I can interact with it despite not having electrs. Verifying this through these kinds of logs after running `docker stop electrs` and then starting the app
```
2024-06-03T14:44:05.288081485Z ERROR native::dlc: On-chain sync failed: Reqwest(reqwest::Error { kind: Request, url: Url { scheme: "http", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("localhost")), port: Some(3000), path: "/scripthash/1ddc89617c14192a6fcda71f16e5275e2abe01362b7ee96bc0da82db8d7f6e0a/txs", query: None, fragment: None }, source: hyper::Error(Connect, ConnectError("tcp connect error", Os { code: 111, kind: ConnectionRefused, message: "Connection refused" })) })
```

**Comment by holzeis** [comment] 2024-06-03 16:58
> Unless @holzeis was referring to some other loss of functionality rather than just crashing?

Two months ago the app was crashing. If it doesn't do this anymore the bug seems to be closed and we can close this ticket.

**Comment by Restioson** [comment] 2024-06-04 07:54
I've now got it to fail as such:
```
flutter: [INFO] TIME: 2024-06-04T07:53:17.475029Z Successfully stored the contact:  .
2024-06-04T07:53:17.476421442Z  INFO native::api: Creating a new seed in "/home/restioson/.local/share/finance.get10101.app/regtest/seed"
2024-06-04T07:53:17.476810904Z  INFO xxi_node::seed: No seed found. Generating new seed
flutter: [DEBUG] TIME: 2024-06-04T07:53:17.477887Z Registering user with  &
2024-06-04T07:53:17.50028326Z DEBUG native::trade::users: Registering user pubkey="02ce86347e39bc41fbbfff4a4973e4ae50fab42ed2fb0984b0e5657f41b4cb6edb" contact="" referral_code="" version="2.4.5"
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: FfiException(RESULT_ERROR, Failed to register beta program with coordinator

Caused by:
    0: error sending request for url (http://127.0.0.1:8000/api/users): error trying to connect: tcp connect error: Connection refused (os error 111)
    1: error trying to connect: tcp connect error: Connection refused (os error 111)
    2: tcp connect error: Connection refused (os error 111)
    3: Connection refused (os error 111), null)
#0      FlutterRustBridgeBase._transformRust2DartMessage (package:flutter_rust_bridge/src/basic.dart:129:9)
#1      FlutterRustBridgeBase.executeNormal.<anonymous closure> (package:flutter_rust_bridge/src/basic.dart:70:9)
<asynchronous suspension>
#2      _WelcomeScreenState.setupWallet (package:get_10101/features/welcome/welcome_screen.dart:258:5)
<asynchronous suspension>
#3      _LoadingScreenState.initState.<anonymous closure> (package:get_10101/features/welcome/loading_screen.dart:33:44)
<asynchronous suspension>
#4      _LoadingScreenState.initState.<anonymous closure> (package:get_10101/features/welcome/loading_screen.dart:39:13)
<asynchronous suspension>
```

**Comment by Restioson** [comment] 2024-06-05 08:51
I'm going to close this meanwhile as can't reproduce.

**Closed by Restioson** 2024-06-05 08:51 UTC
Labels: bug
