### ISSUE TITLE
Not enough outbound capacity to establish given contract. Want 61719000 but have 56453000"

### ISSUE THREAD

**Issue by holzeis** [get10101/10101#981] opened 2023-07-22 20:54 UTC
It seems we have an regression in the ui validation rules. I was able to submit an order with insufficient outbound liquidity.

1. Fund wallet with 56300 sats
2. Go long with 18 contracts and leverage 2

Reproduced on test environment.

Note, order simply went to failed without any additional information. Reducing the contracts to 10 made my order succeed.

**Comment by Restioson** [comment] 2023-07-28 08:57
Related to #983 potentially?

**Comment by Restioson** [comment] 2023-08-02 15:10
> order simply went to failed without any additional information

This specifically might have been fixed by #1025 in https://github.com/get10101/10101/commit/6852939404abc53b54709e3fd390e4c4dde0c4b4

**Comment by klochowicz** [comment] 2023-08-07 22:04
I could not reproduce it on the latest master. 

Closing until it appears again.

**Comment by bonomat** [comment] 2023-08-08 06:15
> Closing until it appears again.

You did not close it though 😅

**Closed by bonomat** 2023-08-08 06:15 UTC
Labels: bug, UI

**Comment by klochowicz** [comment] 2023-08-08 15:58
> > Closing until it appears again.
> 
> You did not close it though 😅

ah sorry, I have set it to 'Done' on the project though 🤦🏻‍♂️
