### ISSUE TITLE
Flaky test `force_close_ln_dlc_channel`

### ISSUE THREAD

**Issue by luckysori** [get10101/10101#1243] opened 2023-09-07 04:47 UTC
CI repro [here](https://github.com/get10101/10101/actions/runs/6091875463/job/16533953052?pr=1216#step:8:4931).

**Comment by bonomat** [comment] 2023-09-11 15:33
My assumption is that this was due to the machine being overloaded and bitcoin was not done with processing all mined blocks. In this particular test we are generating quite a few blocks.

I propose to avoid this particular problem simply checking and reacting to the response from bitcoind.

**Comment by klochowicz** [comment] 2023-09-28 00:03
I've added container logs: https://github.com/get10101/10101/pull/1389 .
Meanwhile, I could not reproduce it locally, so I'm closing the issue until it appears again, as it's not directly actionable (hopefully next time we'll get more detailed logs with the PR linked above).

**Closed by klochowicz** 2023-09-28 00:03 UTC
Labels: bug, testing
