### ISSUE TITLE
Same transaction shows simultaneously as pending and confirmed

### ISSUE THREAD

**Issue by klochowicz** [get10101/10101#1313] opened 2023-09-19 03:36 UTC
**Describe the bug**
Instead of having one transaction with its current status, it seems that both old 'pending' and new 'confirmed state for the same transactions are displayed in different rows

**To Reproduce**

1. Fund the wallet on regtest
2. Look at the transactions
3. See that 2 transactions for the same amount are there

**Expected behavior**
I expected having the same transaction only shown with the *latest* status.

**Screenshots**
![IMG_241306E09830-1](https://github.com/get10101/10101/assets/8319440/9d467a1d-1de3-4e31-99af-68dd1098af62)

**Smartphone (please complete the following information):**

- Device: iPhone14
- OS: iOS
- Version [latest regtest]

**Comment by bonomat** [comment] 2023-09-19 07:11
Duplicate of https://github.com/get10101/10101/issues/1254

**Closed by bonomat** 2023-09-19 07:11 UTC
Labels: bug, UI
