### ISSUE TITLE
App fails to start with [firebase_messaging/unknown] An unknown error has occurred.

### ISSUE THREAD

**Issue by holzeis** [get10101/10101#1363] opened 2023-09-23 12:31 UTC
Environment: regtest
Build Number: 2179
Build Version: 1.2.6

`2023-09-23 13:36:33.058  LogLevel.ERROR  Failed to initialise: [firebase_messaging/unknown] An unknown error has occurred. `

The app sometimes fails on line `final fcmToken = await messaging.getToken();`, preventing the node to start.

https://github.com/get10101/10101/blob/2725f19f98615972309162fa5e78cf9389893dcf/mobile/lib/main.dart#L552-L557

Not sure why this is happening only sometimes, but it may be related to https://github.com/get10101/10101/issues/1350. see also https://stackoverflow.com/a/69754276/8643355

**Comment by bonomat** [comment] 2023-09-25 08:37
Let's see if this happens after https://github.com/get10101/10101/pull/1364 is deployed.

**Comment by bonomat** [comment] 2023-09-25 09:56
Also fixed with https://github.com/get10101/10101/pull/1364

**Comment by klochowicz** [comment] 2023-09-25 19:11
the issue happened to me whilst rebasing my current work locally:


```
2023-09-25 12:07:19.362 10101[78035:381066] FLTFirebaseMessaging: An error occurred while calling method Messaging#getToken, errorOrNil => {
    NSLocalizedFailureReason = "No APNS token specified before fetching FCM Token";
}
flutter: 2023-09-25 12:07:19.653  LogLevel.ERROR  Error fetching FCM token: [firebase_messaging/unknown] An unknown error has occurred.

```

the root cause of this issue is that we assume that everyone will have the push notifications enabled in order to start the backend, which should not be the case.

**Comment by bonomat** [comment] 2023-09-26 14:41
Fixed.

**Closed by bonomat** 2023-09-26 14:41 UTC
Labels: bug
