### ISSUE TITLE
Fix the flutter exception that is thrown in the trade bottom sheets when editing values

### ISSUE THREAD

**Issue by da-kami** [get10101/10101#402] opened 2023-04-12 21:55 UTC
After making the `TradeBottomSheetTab` stateful in #397  we keep seeing this exception in the logs (when modifying the `margin`; we also see it when modifying the `quantity`, but slightly different because it is always triggered by the other text field):

```
══╡ EXCEPTION CAUGHT BY FOUNDATION LIBRARY ╞════════════════════════════════════════════════════════
The following assertion was thrown while dispatching notifications for TextEditingController:
setState() or markNeedsBuild() called during build.
This Form widget cannot be marked as needing to build because the framework is already in the
process of building widgets. A widget can be marked as needing to be built during the build phase
only if one of its ancestors is currently building. This exception is allowed because the framework
builds parent widgets before children, which means a dirty descendant will always be built.
Otherwise, the framework might not visit this widget during this build phase.
The widget on which setState() or markNeedsBuild() was called was:
  Form-[LabeledGlobalKey<FormState>#3fa9e]
The widget which was currently being built when the offending call was made was:
  DoubleTextInputFormField

When the exception was thrown, this was the stack:

...
```
When using `TextEdigintController`s and a `Form` it is recommended to have a `Stateful` widget.

Part of the problem comes from the complexity of having two text fields that update each other - sounds easy, but is actually quite complex. But even without editing both fields we can run into the exception of triggering multiple builds. 

I added `print` statements to see how often certain code pathes (onChange, and build) are triggered and they are triggered too often - but I just don't understand how. In many cases I did not even interact with the UI and somehow it triggered a rebuild. I am not sure what in our setup triggers this, but something is and I don't have the time to look into this now.

---

Daniel's conclusion:

The problem must be related to using the providor's `Selector` in combination with the `FormTextFields` and validation. I stopped investigating because it's too time intense. 

Recommendation:

1. Take a step back
2. Keep the requirements for the trade bottom sheet screens (how the text fields should behave, ...)
3. Re-designing the implementation from the ground up keeping the requirements in mind

**Comment by klochowicz** [comment] 2023-04-18 19:28
@holzeis I have reopened the issue after confirming that @da-kami 's work didn't fix this issue.

**Comment by bonomat** [comment] 2023-07-05 12:40
I think this should be fixed.

**Comment by bonomat** [comment] 2023-08-05 09:06
Problem seems to be solved. I can't reproduce the exception neither on the iphone simulator nor on macos native

**Closed by bonomat** 2023-08-05 09:06 UTC
Labels: Technical Debt
