### ISSUE TITLE
Make position expiry configurable

### ISSUE THREAD

**Issue by holzeis** [get10101/10101#1029] opened 2023-07-30 08:34 UTC
At the moment any position expires at the next days midnight. Meaning that a position is at least 24 hours and at most 48 hours open.

This logic is hard-coded. It would be great if we could configure that, not only for testing purposes.

**Comment by klochowicz** [comment] 2023-07-31 18:17
Duplicate of #935

**Comment by holzeis** [comment] 2023-07-31 19:33
> Duplicate of #935 

This is not a duplicate. The order expiry is unrelated to the position expiry.

**Comment by klochowicz** [comment] 2023-08-06 21:04
> > Duplicate of #935
> 
> This is not a duplicate. The order expiry is unrelated to the position expiry.

it's different, but of course it's related; they should be changed via the same API, and most likely tackled at the same time.

**Comment by bonomat** [comment] 2023-08-07 07:25
I don't think so. 
The order is the thing which is in the orderbook, the position is the thing the trader has locally. 
Both expiries are different, e.g. the order may expire in 1 minute, while the position expires in ~24h.

**Comment by klochowicz** [comment] 2023-08-07 16:19
Aren't they both essentially terms, on which maker wants to offer anything? 
Of course they're used in different times, but I would fully expect for both being configurable from the maker side. 
After all, in the ideal world they'd set how long their orders are active and how long to set positions up for (minus platform constraints).

**Comment by bonomat** [comment] 2023-08-28 09:22
Hi @klochowicz : you've been assigned to this since 2 weeks. Are you working on it? If not, please unassign yourself

**Comment by klochowicz** [comment] 2023-08-28 16:25
> Hi @klochowicz : you've been assigned to this since 2 weeks. Are you working on it? If not, please unassign yourself

I was 90% in, but then noticed that it was removed from iteration *after* last objective alignment, so I focused on more pressing things. I will post it today, because it's close to completion.

**Comment by bonomat** [comment] 2023-08-28 17:32
Sounds good. Thanks for clarification.

**Comment by bonomat** [comment] 2023-09-05 07:04
Deprioritized for now.

**Comment by klochowicz** [comment] 2023-09-05 23:03
I've linked the work that I've done on this ticket, to whoever wants to pick it up.

**Comment by holzeis** [comment] 2023-09-12 15:03
Can we close that ticket, now that we are using a logic to calculate the expiry time?

**Comment by bonomat** [comment] 2023-09-12 17:48
I think so, changing this calculation logic with a config might be a bit too complex.

**Closed by bonomat** 2023-09-12 17:48 UTC

**Comment by bonomat** [comment] 2023-09-13 11:57
I think so, changing this calculation logic with a config might be a bit too complex.
