### ISSUE TITLE
Deposit funds (initially)

### ISSUE THREAD

**Issue by 1010Tom** [get10101/10101#69] opened 2023-01-31 03:24 UTC
When initially funding the wallet we have a nice little wizard: 

https://user-images.githubusercontent.com/88702308/215655149-143e56da-7877-425f-b4fd-8aa15aedc330.mov

**Comment by holzeis** [comment] 2023-03-01 10:03
Looks like this is a duplicate of #71 ? cc: @bonomat @da-kami

**Comment by bonomat** [comment] 2023-03-02 22:15
> Looks like this is a duplicate of #71 ? cc: @bonomat @da-kami

The idea here was that for the initial depositing funds we have a slightly different flow than for receiving funds later on. Doing so allows us to explain a bit more what is happening etc.

**Comment by bonomat** [comment] 2023-03-07 04:33
Closed as it's already working good enough.

**Closed by bonomat** 2023-03-07 04:33 UTC
Labels: Mobile
