### ISSUE TITLE
Use payout calculation when calculating close position trade amount in TX history

### ISSUE THREAD

**Issue by luckysori** [get10101/10101#311] opened 2023-03-22 03:59 UTC
At the moment we use the margin calculation, which is incorrect because it doesn't include the PNL.

See: https://github.com/get10101/10101/pull/307#discussion_r1144213133.

**Comment by holzeis** [comment] 2023-03-22 12:53
@luckysori is this a duplicate of #301 ?

**Comment by luckysori** [comment] 2023-03-22 20:54
It's similar but this one was just meant for displaying in the transaction history. I'll make that clearer.

**Comment by da-kami** [comment] 2023-03-23 04:53
We should be able to use the `payout` function that will be introduced in https://github.com/get10101/10101/pull/305

**Closed** 2023-04-11 13:26 UTC
Labels: Mobile, MVP
