### ISSUE TITLE
Position stuck in `Closing` forever in app

### ISSUE THREAD

**Issue by da-kami** [get10101/10101#558] opened 2023-04-29 13:26 UTC
I had a position open for about 20 hours, when closing everything looked good, but the order remained in `Open` forever, and the position forever in `Closing`. 

I did not find any problem - neither in the app nor the coordinator - here's the [relevant timeframe Grafana link](https://itchysats.grafana.net/goto/-fkdFvy4R?orgId=1)

App logs:

```
| 2023-04-29 09:05:01.848 | LogLevel.DEBUG | New message from orderbook msg: {"Match":{"order_id":"7418d745-2e99-4124-84a1-4c2652a146a6","expiry_timestamp":[2023,121,0,0,0,0,0,0,0],"oracle_pk":"16f88cf7d21e6c0f46bcbc983a4e3b19726c6c98858cc31c83551a88fde171c0","matches":[{"order_id":"40885ca4-3a6d-4228-aff0-59408abf3273","quantity":0.59,"pubkey":"03f75f318471d32d39be3c86c622e2c51bd5731bf95f98aaa3ed5d6e1c0025927f","execution_price":29292.5}]}} 
| 2023-04-29 09:05:01.850 | LogLevel.INFO | Received match from orderbook order_id: 7418d745-2e99-4124-84a1-4c2652a146a6 
| 2023-04-29 09:05:01.853 | LogLevel.DEBUG | Filling order with id: 7418d745-2e99-4124-84a1-4c2652a146a6 filled: FilledWith { order_id: 7418d745-2e99-4124-84a1-4c2652a146a6, expiry_timestamp: 2023-05-01 0:00:00.0 +00:00:00, oracle_pk: XOnlyPublicKey(c071e1fd881a55831cc38c85986c6c72193b4e3a98bcbc460f6c1ed2f78cf8167458a18010faf718756c69de33ee9e38a0d3f0ad48befa58e23a4b1f843e08be), matches: [Match { order_id: 40885ca4-3a6d-4228-aff0-59408abf3273, quantity: 0.59, pubkey: PublicKey(7f9225001c6e5deda3aa985ff91b73d51bc5e222c6863cbe392dd37184315ff717604e65ac604059feb52794ce49f25f078cae6e785ecb1129b63ff08d969ffd), execution_price: 29292.5 }] },order: Order { id: 7418d745-2e99-4124-84a1-4c2652a146a6, leverage: 2.0, quantity: 0.58616, contract_symbol: BtcUsd, direction: Long, order_type: Market, state: Initial, creation_timestamp: 2023-04-29 13:05:01.0 +00:00:00 } 
| 2023-04-29 09:05:01.854 | LogLevel.INFO | Updated order state new_state: Filling,order_id: 7418d745-2e99-4124-84a1-4c2652a146a6 
| 2023-04-29 09:05:01.856 | LogLevel.DEBUG | Publishing event OrderUpdateNotification(Order { id: 7418d745-2e99-4124-84a1-4c2652a146a6, leverage: 2.0, quantity: 0.58616, contract_symbol: BtcUsd, direction: Long, order_type: Market, state: Filling { execution_price: 29292.5 }, creation_timestamp: 2023-04-29 13:05:01.0 +00:00:00 })  
| 2023-04-29 09:05:01.858 | LogLevel.DEBUG | Ignoring latest state update candidate: Open,current_state: Filling 
| 2023-04-29 09:05:01.859 | LogLevel.DEBUG | Publishing event OrderUpdateNotification(Order { id: 7418d745-2e99-4124-84a1-4c2652a146a6, leverage: 2.0, quantity: 0.58616, contract_symbol: BtcUsd, direction: Long, order_type: Market, state: Filling { execution_price: 29292.5 }, creation_timestamp: 2023-04-29 13:05:01.0 +00:00:00 })  
| 2023-04-29 09:05:01.976 | LogLevel.INFO | Sent trade request to coordinator successfully  
| 2023-04-29 09:05:03.467 | LogLevel.INFO | Getting all payments payment_hashes: [PaymentHash([20, 121, 204, 154, 210, 254, 41, 115, 156, 178, 237, 122, 181, 34, 189, 134, 45, 233, 26, 126, 4, 194, 39, 87, 205, 115, 185, 225, 123, 107, 104, 96])] 
| 2023-04-29 09:05:03.471 | LogLevel.INFO | Off-chain payment details details: PaymentDetails { payment_hash: PaymentHash([20, 121, 204, 154, 210, 254, 41, 115, 156, 178, 237, 122, 181, 34, 189, 134, 45, 233, 26, 126, 4, 194, 39, 87, 205, 115, 185, 225, 123, 107, 104, 96]), status: Succeeded, flow: Inbound, amount_msat: Some(10000000), timestamp: 2023-04-27 18:12:26.0 +00:00:00 } 
| 2023-04-29 09:05:03.474 | LogLevel.DEBUG | Publishing event WalletInfoUpdateNotification(WalletInfo { balances: Balances { on_chain: 0, lightning: 7321 }, history: [WalletHistoryItem { flow: Outbound, amount_sats: 1000, timestamp: 1682714071, status: Confirmed, wallet_type: Trade { order_id: "e0a92e22-f3ff-4f90-a78b-6cc9ce1eb126" } }, WalletHistoryItem { flow: Inbound, amount_sats: 1007, timestamp: 1682711845, status: Confirmed, wallet_type: Trade { order_id: "5c615e36-0f2c-40ed-8679-ed71e4548768" } }, WalletHistoryItem { flow: Outbound, amount_sats: 1000, timestamp: 1682698020, status: Confirmed, wallet_type: Trade { order_id: "2c9e882f-62bd-4580-8510-dc0a0da21e4c" } }, WalletHistoryItem { flow: Inbound, amount_sats: 971, timestamp: 1682689958, status: Confirmed, wallet_type: Trade { order_id: "efdd73df-91d0-4dae-bcfe-f1dee51f35e0" } }, WalletHistoryItem { flow: Outbound, amount_sats: 1000, timestamp: 1682649684, status: Confirmed, wallet_type: Trade { order_id: "988fc7cb-b500-4b22-8afc-877c0aa0eed4" } }, WalletHistoryItem { flow: Inbound, amount_sats: 1009, timestamp: 1682626913, status: Confirmed, wallet_type: Trade { order_id: "56ca1b88-4a88-46e1-8d92-891e28a071db" } }, WalletHistoryItem { flow: Outbound, amount_sats: 1000, timestamp: 1682619256, status: Confirmed, wallet_type: Trade { order_id: "e89ed97d-b987-4a2d-8d99-d5ee1db32cbd" } }, WalletHistoryItem { flow: Inbound, amount_sats: 10000, timestamp: 1682619146, status: Confirmed, wallet_type: Lightning { payment_hash: "1479cc9ad2fe29739cb2ed7ab522bd862de91a7e04c22757cd73b9e17b6b6860" } }] })  
| 2023-04-29 09:05:03.485 | LogLevel.DEBUG | lightning::ln::channelmanager: Marking channels with 022ae8dbec1caa4dac93f07f2ebf5ad7a5dd08d375b79f11095e81b065c2155156 disconnected and generating channel_updates. We believe we can make future connections to this peer.  
| 2023-04-29 09:05:03.489 | LogLevel.DEBUG | Connection lost; reconnecting peer: 022ae8dbec1caa4dac93f07f2ebf5ad7a5dd08d375b79f11095e81b065c2155156@34.30.20.202:9045,reconnect_interval: 1s 
| 2023-04-29 09:05:04.478 | LogLevel.DEBUG | Setting up connection peer: 022ae8dbec1caa4dac93f07f2ebf5ad7a5dd08d375b79f11095e81b065c2155156@34.30.20.202:9045 
| 2023-04-29 09:05:04.525 | LogLevel.DEBUG | Connection setup completed peer: 022ae8dbec1caa4dac93f07f2ebf5ad7a5dd08d375b79f11095e81b065c2155156@34.30.20.202:9045 
| 2023-04-29 09:05:04.528 | LogLevel.DEBUG | Waiting to confirm established connection peer: 022ae8dbec1caa4dac93f07f2ebf5ad7a5dd08d375b79f11095e81b065c2155156@34.30.20.202:9045 
| 2023-04-29 09:05:04.569 | LogLevel.DEBUG | lightning::ln::peer_handler: Finished noise handshake for connection with 022ae8dbec1caa4dac93f07f2ebf5ad7a5dd08d375b79f11095e81b065c2155156  
| 2023-04-29 09:05:04.606 | LogLevel.INFO | lightning::ln::peer_handler: Received peer Init message from 022ae8dbec1caa4dac93f07f2ebf5ad7a5dd08d375b79f11095e81b065c2155156: DataLossProtect: supported, InitialRoutingSync: not supported, UpfrontShutdownScript: supported, GossipQueries: supported, VariableLengthOnion: required, StaticRemoteKey: required, PaymentSecret: required, BasicMPP: supported, Wumbo: supported, ShutdownAnySegwit: supported, OnionMessages: not supported, ChannelType: supported, SCIDPrivacy: supported, ZeroConf: supported, unknown flags: none  
| 2023-04-29 09:05:04.609 | LogLevel.DEBUG | lightning::ln::channelmanager: Generating channel_reestablish events for 022ae8dbec1caa4dac93f07f2ebf5ad7a5dd08d375b79f11095e81b065c2155156  
| 2023-04-29 09:05:04.614 | LogLevel.DEBUG | lightning::ln::peer_handler: Handling SendChannelReestablish event in peer_handler for node 022ae8dbec1caa4dac93f07f2ebf5ad7a5dd08d375b79f11095e81b065c2155156 for channel b87175b38ef98e4601fa5818999b33f7f473997b33f5123353ac1a6c46afa8db  
| 2023-04-29 09:05:04.658 | LogLevel.DEBUG | lightning::ln::channel: Reconnected channel b87175b38ef98e4601fa5818999b33f7f473997b33f5123353ac1a6c46afa8db with no loss  
| 2023-04-29 09:05:04.706 | LogLevel.DEBUG | lightning::ln::channelmanager: Received channel_update for channel b87175b38ef98e4601fa5818999b33f7f473997b33f5123353ac1a6c46afa8db.  
| 2023-04-29 09:05:04.707 | LogLevel.DEBUG | lightning::ln::peer_handler: Error handling message from 022ae8dbec1caa4dac93f07f2ebf5ad7a5dd08d375b79f11095e81b065c2155156; ignoring: Couldn't find channel for update  
| 2023-04-29 09:05:05.529 | LogLevel.INFO | Connection established peer: 022ae8dbec1caa4dac93f07f2ebf5ad7a5dd08d375b79f11095e81b065c2155156@34.30.20.202:9045 
```

Coordinator:

I see the request being handled, but there is no error :/ 

```
	2023-04-29 09:05:02.497	(no unique labels)	
{"timestamp":"2023-04-29T13:05:02.497582398Z","level":"INFO","fields":{"message":"Received peer Init message from 02a8dda36be280ad3ed7f7c0a039f2fa8c565272dfe51b5e80986e34cc9ea41f97: DataLossProtect: supported, InitialRoutingSync: not supported, UpfrontShutdownScript: supported, GossipQueries: supported, VariableLengthOnion: required, StaticRemoteKey: required, PaymentSecret: required, BasicMPP: supported, Wumbo: supported, ShutdownAnySegwit: supported, OnionMessages: not supported, ChannelType: supported, SCIDPrivacy: supported, ZeroConf: supported, unknown flags: none","log.target":"lightning::ln::peer_handler","log.module_path":"lightning::ln::peer_handler","log.file":"/home/runner/.cargo/git/checkouts/rust-lightning-8ffd0e8d14b5d2cc/6df5761/lightning/src/ln/peer_handler.rs","log.line":1237},"target":"lightning::ln::peer_handler"}
	
	
2023-04-29 09:05:02.466	(no unique labels)	
{"timestamp":"2023-04-29T13:05:02.466729736Z","level":"DEBUG","fields":{"message":"Finished noise handshake for connection with 02a8dda36be280ad3ed7f7c0a039f2fa8c565272dfe51b5e80986e34cc9ea41f97","log.target":"lightning::ln::peer_handler","log.module_path":"lightning::ln::peer_handler","log.file":"/home/runner/.cargo/git/checkouts/rust-lightning-8ffd0e8d14b5d2cc/6df5761/lightning/src/ln/peer_handler.rs","log.line":1109},"target":"lightning::ln::peer_handler"}
	
	
2023-04-29 09:04:59.837	(no unique labels)	
{"timestamp":"2023-04-29T13:04:59.837190356Z","level":"DEBUG","fields":{"message":"Closing position of 1001 with 02a8dda36be280ad3ed7f7c0a039f2fa8c565272dfe51b5e80986e34cc9ea41f97","position":"Position { id: 24, contract_symbol: BtcUsd, leverage: 2.0, quantity: 0.58616, direction: Short, average_entry_price: 29308.0, liquidation_price: 58616.0, position_state: Open, collateral: 2000, creation_timestamp: 2023-04-28 20:34:30.960316 +00:00:00, expiry_timestamp: 2023-04-30 0:00:00.0 +00:00:00, update_timestamp: 2023-04-28 20:34:30.960316 +00:00:00, trader: PublicKey(971fa49ecc346e98805e1be5df7252568cfaf239a0c0f7d73ead80e26ba3dda81462629888749f1bb7e843bb1f61e07b67f946de4ddf1b85284be6c31ad51746) }","channel_id":"b87175b38ef98e4601fa5818999b33f7f473997b33f5123353ac1a6c46afa8db","accept_settlement_amount":"1001"},"target":"coordinator::node"}
	
	
2023-04-29 09:04:59.835	(no unique labels)	
{"timestamp":"2023-04-29T13:04:59.835364893Z","level":"INFO","fields":{"message":"Closing position","trade_params":"TradeParams { pubkey: PublicKey(971fa49ecc346e98805e1be5df7252568cfaf239a0c0f7d73ead80e26ba3dda81462629888749f1bb7e843bb1f61e07b67f946de4ddf1b85284be6c31ad51746), contract_symbol: BtcUsd, leverage: 2.0, quantity: 0.58616, direction: Long, filled_with: FilledWith { order_id: 7418d745-2e99-4124-84a1-4c2652a146a6, expiry_timestamp: 2023-05-01 0:00:00.0 +00:00:00, oracle_pk: XOnlyPublicKey(c071e1fd881a55831cc38c85986c6c72193b4e3a98bcbc460f6c1ed2f78cf8167458a18010faf718756c69de33ee9e38a0d3f0ad48befa58e23a4b1f843e08be), matches: [Match { order_id: 40885ca4-3a6d-4228-aff0-59408abf3273, quantity: 0.59, pubkey: PublicKey(7f9225001c6e5deda3aa985ff91b73d51bc5e222c6863cbe392dd37184315ff717604e65ac604059feb52794ce49f25f078cae6e785ecb1129b63ff08d969ffd), execution_price: 29292.5 }] } }","channel_id":"b87175b38ef98e4601fa5818999b33f7f473997b33f5123353ac1a6c46afa8db","peer_id":"02a8dda36be280ad3ed7f7c0a039f2fa8c565272dfe51b5e80986e34cc9ea41f97"},"target":"coordinator::node"}
	
	
2023-04-29 09:04:56.683	(no unique labels)	
{"timestamp":"2023-04-29T13:04:56.682974438Z","level":"DEBUG","fields":{"message":"Marking channels with 02a8dda36be280ad3ed7f7c0a039f2fa8c565272dfe51b5e80986e34cc9ea41f97 disconnected and generating channel_updates. We believe we can make future connections to this peer.","log.target":"lightning::ln::channelmanager","log.module_path":"lightning::ln::channelmanager","log.file":"/home/runner/.cargo/git/checkouts/rust-lightning-8ffd0e8d14b5d2cc/6df5761/lightning/src/ln/channelmanager.rs","log.line":6553},"target":"lightning::ln::channelmanager"}
```

**Comment by da-kami** [comment] 2023-04-29 13:35
I checked in the coordinator database, the position is still open. 
Seems the protocol just did not finish executing. 
Because we never reset the position state to open in the app I am stuck though.

**Comment by da-kami** [comment] 2023-04-30 01:52
This ticket is actually likely not related to #554 - the problem here is just that I lost connection while closing he position and then the app is stuck. 
Should be able to reset position to open in the app and then just try again (the channel should be fine from what we know :)

**Comment by klochowicz** [comment] 2023-05-01 18:22
I had a brainstorming session with @luckysori and we've settled on:
- removing `PositionState` from db.
- deriving `PositionState` from the `Order`(local order on the app)
- during startup, reconciling the `Order` state (simple heuristic: if you just started the app, and the order is filled but the position is still open, set the Order to failed.

The above will simply throw the ball back to the user. We can try to reconcile periodically or query the other party whether they are still acting on it.

Any feedback to the heuristic above would be appreciated - right now I'm just operating under our beta constraint that the Orders are not filled in between app restarts.

**Comment by bonomat** [comment] 2023-05-01 18:52
From a stats/metrics perspective it would be nice to have the `position_state` in the db. Otherwise it is hard to make sense from the data in the DB alone.

**Comment by klochowicz** [comment] 2023-05-01 18:59
> From a stats/metrics perspective it would be nice to have the `position_state` in the db. Otherwise it is hard to make sense from the data in the DB alone.

we're talking about data in the DB of the app, and `position_state` has only `Open/Closing` states. As it stands, we can't conclusively use it for stats anyway. 

We could still use the same data in DB to derive the `position_state` if we wanted to. 

we're just reducing one source of potential discrepancy in the data - `Order` state is the one that matters here, and on "open" position only matters in relation to the filled/unfilled order.

**Comment by klochowicz** [comment] 2023-05-01 20:48
@luckysori I've opened a separate issue to deal with the tech debt here - the reasoning is still valid, but with the #567 fix we get rid of the root cause, so I don't think the issue will be critical anymore (it should still be addressed though).

**Comment by klochowicz** [comment] 2023-05-02 15:41
@holzeis pointed out that fixing an issue in rust-dlc will deal with this problem most comprehensively

https://matrix.to/#/!YOUZSBmuJuaGzmxzaA:matrix.org/$DH8KXYw_90J8QZDzohruFEv1y3IALBNmyNMhn30IgXw?via=matrix.org

#567 PR only deals with spurious network errors when coordinator is not reachable at all, whereas Tibo's fix in rust-dlc fixes an issue that encountered most frequently.

I'm reprioritising my work to incorporate that fix right away.

**Comment by klochowicz** [comment] 2023-05-05 17:22
Both rust-dlc and our `submit_order()` logic got updated. 

There's nothing more actionable to deal with at this stage - I'm closing this issue tentatively until it happens again.

**Closed by klochowicz** 2023-05-05 17:22 UTC
Labels: bug, MVP, critical
