### ISSUE TITLE
Panic in `rust-lightning` when processing subchannel accept message

### ISSUE THREAD

**Issue by holzeis** [get10101/10101#760] opened 2023-06-10 14:29 UTC
The coordinator force closes the channel after the dlc has been accepted by the phone and killed afterwards. This bugs seems to be a regression as a similar bug has already been fixed with https://github.com/get10101/10101/issues/352

## How to reproduce

1. Fund wallet
2. Open a position
3. Kill the app after the dlc was accepted by the phone.

[app logs]
```
| 2023-06-10 09:32:29.822 | LogLevel.INFO | Accepting DLC channel offer channel_id: 66c051a9c97f36e95fbcb30ba9465e9bf10e131d0c7440ed0361dc95a9d789cd 
| 2023-06-10 09:32:29.824 | LogLevel.INFO | lightning::chain::channelmonitor: Applying update to monitor 66c051a9c97f36e95fbcb30ba9465e9bf10e131d0c7440ed0361dc95a9d789cd, bringing update_id from 66 to 67 with 1 changes.  
| 2023-06-10 09:32:29.834 | LogLevel.DEBUG | lightning::ln::channel: Restored monitor updating in channel 66c051a9c97f36e95fbcb30ba9465e9bf10e131d0c7440ed0361dc95a9d789cd resulting in a commitment update and no RAA, with RAA first  
| 2023-06-10 09:32:30.009 | LogLevel.DEBUG | Broadcasting node announcement inc_connection_addresses: [IPv4 { addr: [0, 0, 0, 0], port: 57381 }] 
| 2023-06-10 09:32:30.009 | LogLevel.DEBUG | lightning::ln::peer_handler: Broadcasting NodeAnnouncement after passing it to our own RoutingMessageHandler.  
| 2023-06-10 09:32:30.010 | LogLevel.DEBUG | lightning::ln::peer_handler: DONE Broadcasting NodeAnnouncement after passing it to our own RoutingMessageHandler.  
| 2023-06-10 09:32:30.413 | LogLevel.INFO | lightning_transaction_sync::esplora: Starting transaction sync.  
| 2023-06-10 09:32:31.052 | LogLevel.INFO | lightning_transaction_sync::esplora: Finished transaction sync.  
| 2023-06-10 09:32:31.053 | LogLevel.INFO | Background sync of Lightning wallet finished in 638ms.  
```

4. Start the app again

[app logs]
```
| 2023-06-10 09:32:54.548 | LogLevel.INFO | lightning::ln::peer_handler: Received peer Init message from 03507b924dae6595cfb78492489978127c5f1e3877848564de2015cd6d41375802: DataLossProtect: supported, InitialRoutingSync: not supported, UpfrontShutdownScript: supported, GossipQueries: supported, VariableLengthOnion: required, StaticRemoteKey: required, PaymentSecret: required, BasicMPP: supported, Wumbo: supported, AnchorsZeroFeeHtlcTx: not supported, ShutdownAnySegwit: supported, OnionMessages: not supported, ChannelType: supported, SCIDPrivacy: supported, ZeroConf: supported, unknown flags: none  
| 2023-06-10 09:32:54.550 | LogLevel.DEBUG | lightning::ln::channelmanager: Generating channel_reestablish events for 03507b924dae6595cfb78492489978127c5f1e3877848564de2015cd6d41375802  
| 2023-06-10 09:32:54.551 | LogLevel.DEBUG | lightning::ln::peer_handler: Handling SendChannelReestablish event in peer_handler for node 03507b924dae6595cfb78492489978127c5f1e3877848564de2015cd6d41375802 for channel 66c051a9c97f36e95fbcb30ba9465e9bf10e131d0c7440ed0361dc95a9d789cd  
| 2023-06-10 09:32:54.683 | LogLevel.INFO | Connection established peer: 03507b924dae6595cfb78492489978127c5f1e3877848564de2015cd6d41375802@35.189.57.114:9045 
| 2023-06-10 09:32:55.480 | LogLevel.DEBUG | lightning::ln::peer_handler: Got Err message from 03507b924dae6595cfb78492489978127c5f1e3877848564de2015cd6d41375802: Got a message for a channel from the wrong node! No such channel for the passed counterparty_node_id 038471a17a177a3e642fab5fb0c64f025fd5ce6beb980b3f45cfa726dc83bff6d2  
| 2023-06-10 09:32:55.481 | LogLevel.ERROR | lightning::ln::channelmanager: Force-closing channel 66c051a9c97f36e95fbcb30ba9465e9bf10e131d0c7440ed0361dc95a9d789cd  
| 2023-06-10 09:32:55.482 | LogLevel.DEBUG | lightning::ln::channelmanager: Finishing force-closure of channel with 0 HTLCs to fail  
| 2023-06-10 09:32:55.483 | LogLevel.INFO | lightning::chain::channelmonitor: Applying update to monitor 66c051a9c97f36e95fbcb30ba9465e9bf10e131d0c7440ed0361dc95a9d789cd, bringing update_id from 67 to 68 with 1 changes.  
| 2023-06-10 09:32:55.485 | LogLevel.INFO | lightning::chain::channelmonitor: Broadcasting local commitment tx with txid 334bc00ef117aa31b79d487a9e025e289e7ed02758ec7bf08813e841725c311a  
| 2023-06-10 09:32:55.486 | LogLevel.INFO | Broadcasting transaction raw_tx: 0200000000010166c051a9c97f36e95fbcb30ba9465e9bf10e131d0c7440ed0361dc95a9d789cd000000000019c31580025f71010000000000220020b17227493baad26083146c2a32d2fc0c245212ba8a1b47502ca1f0dc7afe0a2d2a9b0100000000001600140f53d27d2de1ae2b526bf393778fa7d78c9948900400473044022048e01839f277e9d971f2676251d87e9f47f2be0fcd8afb9be8acb495091c37f9022054ab5842cbfc42cb5fa537bfd5fbb860d6d348b8f61f7fb6d3ba52bf884bdcea0147304402205df15d65afba3b6dc86d1da8c80dcc017776cb42f1572252246e79c53f88ccee02205a5dd0248dfd4ce5c75a862b5e3820a324063de2d9672d108153e6c9d8472e2401475221024fc24289c845af934e47c6c454eab55c2b6dfbfedf40f77307443a1c2d95bdb8210291e7a1e7e83a4f37d953f2a8d33f9a0ec81d898bd2eaf17b39f4f60bc086505452ae75321620,txid: 334bc00ef117aa31b79d487a9e025e289e7ed02758ec7bf08813e841725c311a 
| 2023-06-10 09:32:56.550 | LogLevel.ERROR | Failed to broadcast transaction: Esplora client error: HttpResponse(404)  
| 2023-06-10 09:33:07.299 | LogLevel.DEBUG | Broadcasting node announcement inc_connection_addresses: [IPv4 { addr: [0, 0, 0, 0], port: 61293 }] 
| 2023-06-10 09:33:07.300 | LogLevel.DEBUG | lightning::ln::peer_handler: Broadcasting NodeAnnouncement after passing it to our own RoutingMessageHandler.  
| 2023-06-10 09:33:07.301 | LogLevel.DEBUG | lightning::ln::peer_handler: DONE Broadcasting NodeAnnouncement after passing it to our own RoutingMessageHandler.  
| 2023-06-10 09:33:08.675 | LogLevel.INFO | lightning::chain::channelmonitor: Channel 66c051a9c97f36e95fbcb30ba9465e9bf10e131d0c7440ed0361dc95a9d789cd closed by funding output spend in txid 5bd65a0ae5225c6333252e4d2c1e994ea3cd72bf3867ab6515fac9ebc04da78f.  
| 2023-06-10 09:33:08.677 | LogLevel.INFO | lightning::chain::channelmonitor: Got broadcast of non-revoked counterparty commitment transaction 5bd65a0ae5225c6333252e4d2c1e994ea3cd72bf3867ab6515fac9ebc04da78f  
| 2023-06-10 09:33:08.678 | LogLevel.INFO | lightning::chain::channelmonitor: Received spendable output StaticPaymentOutput 5bd65a0ae5225c6333252e4d2c1e994ea3cd72bf3867ab6515fac9ebc04da78f:0 marked for spending, spendable at height 2551  
| 2023-06-10 09:33:15.390 | LogLevel.DEBUG | New message from orderbook msg: {"NewOrder":{"id":"a0cc30cd-6a5a-428c-b16b-9a35315ff5b8","price":25596.0,"trader_id":"0222eccb3303dc5e8a13be107594716a11bfa9307f79e09ea769f06ead28e5de8d","taken":false,"direction":"Long","quantity":1000.0,"order_type":"Limit","timestamp":"2023-06-10T07:33:15.233136Z","expiry":"2023-06-10T07:34:15.218642Z"}} 
| 2023-06-10 09:33:15.391 | LogLevel.DEBUG | Publishing event PriceUpdateNotification({BtcUsd: Price { bid: Some(25596), ask: None }})  
| 2023-06-10 09:33:15.393 | LogLevel.DEBUG | New message from orderbook msg: {"DeleteOrder":"08b1ce2e-e75c-4fc9-8412-1cae8bb19ea8"} 
| 2023-06-10 09:33:15.394 | LogLevel.DEBUG | Publishing event PriceUpdateNotification({BtcUsd: Price { bid: Some(25596), ask: None }})  
| 2023-06-10 09:33:15.400 | LogLevel.DEBUG | New message from orderbook msg: {"NewOrder":{"id":"428dfc11-78a0-4ae5-8a57-a6a0c94b0729","price":25797.5,"trader_id":"0222eccb3303dc5e8a13be107594716a11bfa9307f79e09ea769f06ead28e5de8d","taken":false,"direction":"Short","quantity":1000.0,"order_type":"Limit","timestamp":"2023-06-10T07:33:15.242385Z","expiry":"2023-06-10T07:34:15.241363Z"}} 
| 2023-06-10 09:33:15.400 | LogLevel.DEBUG | Publishing event PriceUpdateNotification({BtcUsd: Price { bid: Some(25596), ask: Some(25797.5) }})  
| 2023-06-10 09:33:15.401 | LogLevel.DEBUG | New message from orderbook msg: {"DeleteOrder":"f7abf4d2-9465-4c08-b8fc-331f795f1091"} 
| 2023-06-10 09:33:15.401 | LogLevel.DEBUG | Publishing event PriceUpdateNotification({BtcUsd: Price { bid: Some(25596), ask: Some(25797.5) }})  
| 2023-06-10 09:33:20.258 | LogLevel.INFO | lightning_transaction_sync::esplora: Finished transaction sync.  
| 2023-06-10 09:33:20.259 | LogLevel.INFO | Background sync of Lightning wallet finished in 44874ms.  
| 2023-06-10 09:33:20.271 | LogLevel.INFO | Received event event: ChannelClosed { channel_id: [102, 192, 81, 169, 201, 127, 54, 233, 95, 188, 179, 11, 169, 70, 94, 155, 241, 14, 19, 29, 12, 116, 64, 237, 3, 97, 220, 149, 169, 215, 137, 205], user_channel_id: 0, reason: CounterpartyForceClosed { peer_msg: "Got a message for a channel from the wrong node! No such channel for the passed counterparty_node_id 038471a17a177a3e642fab5fb0c64f025fd5ce6beb980b3f45cfa726dc83bff6d2" } } 
| 2023-06-10 09:33:20.271 | LogLevel.INFO | 
Channel closed channel: 66c051a9c97f36e95fbcb30ba9465e9bf10e131d0c7440ed0361dc95a9d789cd,reason: CounterpartyForceClosed { peer_msg: "Got a message for a channel from the wrong node! No such channel for the passed counterparty_node_id 038471a17a177a3e642fab5fb0c64f025fd5ce6beb980b3f45cfa726dc83bff6d2" } 
| 2023-06-10 09:33:20.271 | LogLevel.DEBUG | Successfully handled event event: "ChannelClosed { channel_id: [102, 192, 81, 169, 201, 127, 54, 233, 95, 188, 179, 11, 169, 70, 94, 155, 241, 14, 19, 29, 12, 116, 64, 237, 3, 97, 220, 149, 169, 215, 137, 205], user_channel_id: 0, reason: CounterpartyForceClosed { peer_msg: \"Got a message for a channel from the wrong node! No such channel for the passed counterparty_node_id 038471a17a177a3e642fab5fb0c64f025fd5ce6beb980b3f45cfa726dc83bff6d2\" } }" 
| 2023-06-10 09:33:20.272 | LogLevel.INFO | Received event event: SpendableOutputs { outputs: [StaticPaymentOutput(StaticPaymentOutputDescriptor { outpoint: OutPoint { txid: 5bd65a0ae5225c6333252e4d2c1e994ea3cd72bf3867ab6515fac9ebc04da78f, index: 0 }, output: TxOut { value: 94559, script_pubkey: Script(OP_0 OP_PUSHBYTES_20 0bc6e83f96405a92324f280a36c540cac465bd92) }, channel_keys_id: [0, 0, 0, 1, 28, 134, 246, 152, 0, 0, 0, 0, 100, 131, 95, 82, 252, 41, 75, 101, 140, 182, 19, 101, 35, 230, 17, 39, 79, 134, 197, 205], channel_value_satoshis: 200000 })] } 
```

## Result

During re-establishing the channel the coordinator does not recognizse the channel for the passed `counterparty_node_id` and force closes it. My phones node_id did not change - see screenshot of settings after the channel has been force closed.

![Image](https://user-images.githubusercontent.com/382048/244875934-d7d572fd-2d9b-4cd0-bfd8-0fabf60a1a14.jpeg)

**Comment by holzeis** [comment] 2023-06-10 14:30
@luckysori might be some regression after fiddling with our rust-dlc fork to fix the deadlock issue?

**Comment by holzeis** [comment] 2023-06-10 17:36
Note, after mining about 400 blocks the funds did not return to my onchain wallet.

**Comment by luckysori** [comment] 2023-06-10 23:58
According to the PR you linked, [this test](https://github.com/get10101/10101/commit/194d2099f6938284ddc5b3ce61e1f9e7c1953e53) reproduced the original issue. Does it fail currently?

**Comment by holzeis** [comment] 2023-06-11 06:27
The test pass on my machine..

**Comment by luckysori** [comment] 2023-06-13 12:16
These are the relevant coordinator logs at that time:

```
{"timestamp":"2023-06-10T07:32:55.06061203Z","level":"ERROR","fields":{"message":"Got a message for a channel from the wrong node! No such channel for the passed counterparty_node_id 038471a17a177a3e642fab5fb0c64f025fd5ce6beb980b3f45cfa726dc83bff6d2","log.target":"lightning::ln::channelmanager","log.module_path":"lightning::ln::channelmanager","log.file":"/home/runner/.cargo/git/checkouts/rust-lightning-8ffd0e8d14b5d2cc/939ebb4/lightning/src/ln/channelmanager.rs","log.line":6454},"target":"lightning::ln::channelmanager"}
{"timestamp":"2023-06-10T07:32:46.452551098Z","level":"INFO","fields":{"message":"\nChannel closed","channel":"66c051a9c97f36e95fbcb30ba9465e9bf10e131d0c7440ed0361dc95a9d789cd","reason":"OutdatedChannelManager"},"target":"ln_dlc_node::ln::event_handler"}
{"timestamp":"2023-06-10T07:32:46.437166622Z","level":"INFO","fields":{"message":"Starting background processor"},"target":"ln_dlc_node::node"}
{"timestamp":"2023-06-10T07:32:35.060357622Z","level":"ERROR","fields":{"message":"Aborting after panic in task","info":"panicked at 'called `Option::unwrap()` on a `None` value', /home/runner/.cargo/git/checkouts/rust-lightning-8ffd0e8d14b5d2cc/939ebb4/lightning/src/ln/channelmanager.rs:1890:45"},"target":"coordinator"}
{"timestamp":"2023-06-10T07:32:28.324329283Z","level":"DEBUG","fields":{"message":"Proposing dlc channel","event_id":"btcusd1686528000"},"target":"coordinator::node","span":{"name":"post_trade"},"spans":[{"name":"post_trade"}]}
```

During the DLC channel setup the coordinator ran into a panic which caused it to restart. Once restarted the corresponding channel was force-closed because of an `OutdatedChannelManager` (inconsistent state?). When the app tried to contact the coordinator about this channel, the coordinator no longer knew about it and so the app correctly force-closed itself.

The underlying issue occurred when `unwrap`ping [here](https://github.com/p2pderivatives/rust-lightning/blob/939ebb43f4d179050d38854bdd1684e96773bcaf/lightning/src/ln/channelmanager.rs#L1890). We should investigate why that might happen.

But in general we have too many `unwrap`s in our fork of `rust-lightning`. We should replace these with proper errors unless we have a very good reason to think something should be infallible.

**Closed** 2023-06-19 13:19 UTC
Labels: bug, MVP, prod-environment
