### ISSUE TITLE
Wallet history details

### ISSUE THREAD

**Issue by da-kami** [get10101/10101#346] opened 2023-03-30 02:57 UTC
Follow up of https://github.com/get10101/10101/issues/67

The wallet history is currently just a very simple list that does not add much information.
Additional information should be displayed when clicking on a wallet history list item (the item unfolds and more information is shown).

See mocks here for details: https://github.com/get10101/10101/issues/66#issuecomment-1457576831

**Comment by klochowicz** [comment] 2023-07-17 05:04
related to #886

**Comment by Restioson** [comment] 2023-07-31 11:12
#872 is a duplicate but has more info - should we close this in favour?

**Comment by bonomat** [comment] 2023-07-31 12:15
Feel free to do this yourself in the future :) 

Duplicate of #872

**Closed by bonomat** 2023-07-31 12:15 UTC
Labels: good first issue, UI
