### ISSUE TITLE
Incorrect balance

### ISSUE THREAD

**Issue by holzeis** [get10101/10101#917] opened 2023-07-06 10:07 UTC
A user reported that his lightning balance is shown incorrectly.

![Image](https://user-images.githubusercontent.com/382048/251402420-a5bcdb5f-deac-4e94-b48c-d8c97f26450c.jpg)

Note the screenshot also includes transactions from a channel history that got force closed. So the +50k, -10k +10 should actually be in the on-chain balance. But haven't been due to another bug.

Funding the app again with 50k should show a balance of only 50k then, but it turns out to now being over 20k more than that.

**Comment by bonomat** [comment] 2023-07-07 06:24
Can you add the user's node id please?

**Comment by holzeis** [comment] 2023-07-07 14:55
> Can you add the user's node id please?

03fc2462114ecab9d98b633011f4986e66a2b441593c4eadaaf40c0aff32738a52

**Comment by da-kami** [comment] 2023-07-10 07:15
Does the user have a position open? Is this just related to the channel reserve that is not shown?

**Comment by holzeis** [comment] 2023-07-11 20:10
I haven't checked, but you can do so by using his pubkey.

**Comment by klochowicz** [comment] 2023-07-25 06:02
I'm closing this issue due to the following:

- the user had channel closures and other failures in between
- I could not reproduced it locally nor on public regtest
- it cannot be reproduced by test due to other bug (https://github.com/get10101/10101/pull/995)

#995 should be taken to completion to verify that we *always* have adequate balance after receiving more money after having a position open.

**Closed by klochowicz** 2023-07-25 06:02 UTC
Labels: bug, prod-environment
